import {
  Activity,
  BookOpen,
  BriefcaseBusiness,
  CalendarDays,
  CheckCircle2,
  ClipboardList,
  Dumbbell,
  Film,
  Flag,
  FolderKanban,
  Gamepad2,
  GraduationCap,
  HeartPulse,
  Inbox,
  Landmark,
  ListChecks,
  Mail,
  MapPin,
  MessageSquareText,
  Moon,
  NotebookPen,
  PiggyBank,
  Pin,
  Popcorn,
  Repeat,
  Sparkles,
  Target,
  Timer,
  Trophy,
  Utensils,
} from "lucide-react";
import type { Domain } from "./types";

export const domains: Domain[] = [
  {
    id: "life",
    title: "Life Project",
    subtitle: "A personal space for care, rhythm, and the life you are building.",
    description: "Track health, hobbies, routines, reminders, and the small signals that keep daily life grounded.",
    accent: "#267565",
    accentSoft: "#e1f1ed",
    icon: HeartPulse,
    previewModules: ["Habits", "Calendar", "Workout", "Journal"],
    summaryItems: [
      { label: "Today", value: "Evening reset", detail: "One personal focus queued" },
      { label: "Next event", value: "Workout block", detail: "Tomorrow morning" },
      { label: "Streak", value: "4 days", detail: "Routine check-ins" },
    ],
    modules: [
      {
        id: "calendar",
        title: "Personal calendar",
        description: "A calm look at personal plans, appointments, and protected time.",
        icon: CalendarDays,
        status: "active",
        items: ["Dinner with family", "Workout block", "Weekend planning"],
        actionLabel: "Review day",
      },
      {
        id: "habits",
        title: "Habits",
        description: "Track routines that make the rest of life easier to keep steady.",
        icon: Repeat,
        status: "active",
        items: ["Hydration", "Reading", "Evening reset"],
      },
      {
        id: "workout",
        title: "Workout tracker",
        description: "Plan sessions, note energy, and keep a simple weekly movement rhythm.",
        icon: Dumbbell,
        status: "active",
        items: ["Strength", "Mobility", "Cardio"],
      },
      {
        id: "goals",
        title: "Personal goals",
        description: "Turn broad intentions into visible next actions and milestones.",
        icon: Target,
        status: "active",
        items: ["Health", "Home", "Creative"],
      },
      {
        id: "hobbies",
        title: "Hobbies",
        description: "Keep track of creative interests, skill practice, and things that feel restorative.",
        icon: Sparkles,
        status: "empty",
        items: ["Add a hobby list to begin."],
      },
      {
        id: "journal",
        title: "Journal",
        description: "A private reflection surface for notes, mood, and daily observations.",
        icon: NotebookPen,
        status: "empty",
        items: ["No entries yet."],
      },
      {
        id: "emails",
        title: "Emails",
        description: "A placeholder for personal inbox triage and follow-ups.",
        icon: Mail,
        status: "coming-soon",
        items: ["Integration-ready preview"],
      },
      {
        id: "finances",
        title: "Finances",
        description: "Simple personal budget notes, upcoming bills, and savings goals.",
        icon: PiggyBank,
        status: "empty",
        items: ["Add monthly targets when ready."],
      },
    ],
  },
  {
    id: "work",
    title: "Work",
    subtitle: "A focused productivity room for priorities, projects, and momentum.",
    description: "Organize current work, deadlines, meeting notes, and progress without turning the page into noise.",
    accent: "#3f5f99",
    accentSoft: "#e7edf7",
    icon: BriefcaseBusiness,
    previewModules: ["Kanban", "Priorities", "Projects", "Focus"],
    summaryItems: [
      { label: "Priority", value: "Ship MVP", detail: "Highest-impact item" },
      { label: "Projects", value: "3 active", detail: "One needs review" },
      { label: "Deadline", value: "Friday", detail: "Planning checkpoint" },
    ],
    modules: [
      {
        id: "kanban",
        title: "Kanban board",
        description: "A compact view of current tasks across next, doing, and done.",
        icon: FolderKanban,
        status: "active",
        items: ["Draft spec", "Build dashboard", "Review polish"],
        actionLabel: "Open board",
      },
      {
        id: "priority",
        title: "Priority queue",
        description: "Keep the next best task obvious when attention is limited.",
        icon: Pin,
        status: "active",
        items: ["Finalize UX", "Smoke test", "Prepare handoff"],
      },
      {
        id: "projects",
        title: "Project tracker",
        description: "Monitor project health, ownership, and next milestone.",
        icon: ClipboardList,
        status: "active",
        items: ["Dashboard MVP", "Team docs", "Design cleanup"],
      },
      {
        id: "todo",
        title: "To-do widget",
        description: "A short task list for today's concrete commitments.",
        icon: ListChecks,
        status: "active",
        items: ["Triage notes", "Send update", "Check build"],
      },
      {
        id: "deadlines",
        title: "Deadlines",
        description: "Upcoming calendar pressure without a full calendar integration.",
        icon: Timer,
        status: "active",
        items: ["Friday demo", "Monday review"],
      },
      {
        id: "notes",
        title: "Meeting summaries",
        description: "Capture decisions, follow-ups, and context after calls.",
        icon: MessageSquareText,
        status: "empty",
        items: ["No meeting notes yet."],
      },
      {
        id: "focus",
        title: "Focus mode",
        description: "A quiet surface for choosing one target and muting the rest.",
        icon: Moon,
        status: "coming-soon",
        items: ["Single-task mode preview"],
      },
      {
        id: "progress",
        title: "Progress overview",
        description: "A simple status snapshot across active workstreams.",
        icon: CheckCircle2,
        status: "active",
        items: ["2 on track", "1 needs attention"],
      },
    ],
  },
  {
    id: "entertainment",
    title: "Entertainment",
    subtitle: "A playful planning space for watching, going out, and making weekends easier.",
    description: "Collect movies, Chicago activities, restaurants, events, and recommendations in one light space.",
    accent: "#9a5c32",
    accentSoft: "#f4ebe3",
    icon: Popcorn,
    previewModules: ["Movies", "Chicago", "Events", "Watchlist"],
    summaryItems: [
      { label: "Weekend idea", value: "Museum + dinner", detail: "Saved for Saturday" },
      { label: "Next event", value: "Live music", detail: "Chicago shortlist" },
      { label: "Watchlist", value: "6 picks", detail: "Two under 90 minutes" },
    ],
    modules: [
      {
        id: "movies",
        title: "Movies",
        description: "Keep a watchlist organized by mood, runtime, and who wants to watch.",
        icon: Film,
        status: "active",
        items: ["Quiet drama", "Comedy night", "Rewatch list"],
        actionLabel: "Pick one",
      },
      {
        id: "chicago",
        title: "Activities in Chicago",
        description: "Static idea board for neighborhoods, exhibits, walks, and low-friction outings.",
        icon: MapPin,
        status: "active",
        items: ["Riverwalk", "Art Institute", "Logan Square"],
      },
      {
        id: "watchlist",
        title: "Watchlist",
        description: "A lightweight queue for films, shows, documentaries, and comfort picks.",
        icon: Inbox,
        status: "active",
        items: ["Short films", "New series", "Sunday comfort"],
      },
      {
        id: "weekend",
        title: "Weekend planner",
        description: "Bundle a food idea, event, and downtime block into a simple plan.",
        icon: CalendarDays,
        status: "empty",
        items: ["No plan set yet."],
      },
      {
        id: "restaurants",
        title: "Restaurants",
        description: "Save places to try by neighborhood, budget, and occasion.",
        icon: Utensils,
        status: "empty",
        items: ["Add a restaurant shortlist."],
      },
      {
        id: "events",
        title: "Events and concerts",
        description: "Track shows, concerts, festivals, and one-night-only plans.",
        icon: Activity,
        status: "coming-soon",
        items: ["Live data can come later."],
      },
      {
        id: "games",
        title: "Games",
        description: "Keep party games, cozy games, and backlog ideas visible.",
        icon: Gamepad2,
        status: "empty",
        items: ["No games saved yet."],
      },
      {
        id: "books",
        title: "Books",
        description: "A relaxed reading shelf for fiction, nonfiction, and recommendations.",
        icon: BookOpen,
        status: "empty",
        items: ["Start a reading list."],
      },
    ],
  },
  {
    id: "study",
    title: "Study",
    subtitle: "A structured learning room for courses, assignments, and exam readiness.",
    description: "Make study work visible: subjects, notes, readings, flashcards, deadlines, and progress.",
    accent: "#6b5a9a",
    accentSoft: "#ece8f7",
    icon: GraduationCap,
    previewModules: ["Courses", "Assignments", "Notes", "Flashcards"],
    summaryItems: [
      { label: "Next task", value: "Reading notes", detail: "Due tomorrow" },
      { label: "Progress", value: "68%", detail: "Current study cycle" },
      { label: "Exam prep", value: "2 weeks", detail: "Practice starts soon" },
    ],
    modules: [
      {
        id: "courses",
        title: "Courses and subjects",
        description: "Group classes, topics, or self-study tracks into clear lanes.",
        icon: Landmark,
        status: "active",
        items: ["Design systems", "Statistics", "Writing"],
        actionLabel: "Review subjects",
      },
      {
        id: "assignments",
        title: "Assignments",
        description: "Track upcoming work, due dates, and submission status.",
        icon: ClipboardList,
        status: "active",
        items: ["Essay outline", "Problem set", "Reading response"],
      },
      {
        id: "study-calendar",
        title: "Study calendar",
        description: "Plan sessions around deadlines without needing a full calendar backend.",
        icon: CalendarDays,
        status: "active",
        items: ["Review block", "Practice quiz", "Office hours"],
      },
      {
        id: "notes",
        title: "Notes",
        description: "Capture lecture notes, summaries, and links to useful references.",
        icon: NotebookPen,
        status: "active",
        items: ["Week 4 summary", "Research notes"],
      },
      {
        id: "flashcards",
        title: "Flashcards",
        description: "Prepare active recall prompts for definitions, formulas, and key ideas.",
        icon: ListChecks,
        status: "coming-soon",
        items: ["Review engine preview"],
      },
      {
        id: "reading",
        title: "Reading list",
        description: "Keep articles, chapters, and books in a study-ready queue.",
        icon: BookOpen,
        status: "empty",
        items: ["No readings queued."],
      },
      {
        id: "exam",
        title: "Exam prep",
        description: "Turn exam dates into practice sessions and confidence checks.",
        icon: Trophy,
        status: "empty",
        items: ["Add an exam date."],
      },
      {
        id: "resources",
        title: "Resource library",
        description: "Collect links, PDFs, videos, and reference material by subject.",
        icon: Flag,
        status: "empty",
        items: ["No resources saved yet."],
      },
    ],
  },
];
